### ISSUE TITLE
simple_html_dom fails when network is slow

### ISSUE THREAD

**Issue by jajupmochi** [xjtudance/xjtudance#1]
When I run [clone_bmyjinghua.php](https://github.com/xjtudance/xjtudance/blob/master/dance_server/php/clone_bmyjinghua.php) in a terminal, if network is slow, it returns following error massage:

`97 articles saved, 112.98292994499s passed.PHP Warning:  file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /data/release/dance/xjtudance/test/php/simple_html_dom.php on line 39
PHP Warning:  file_get_contents(http://bbs.xjtu.edu.cn/BMYAHADSPJYXLKWEMUBMUHOEIRMEEXFFPUUX_B/bbsanc?path=/groups/GROUP_8/dance/M1412293824/M1412300339/M1412300501/M1412300736&item=/M1412301842): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /data/release/dance/xjtudance/test/php/simple_html_dom.php on line 39
PHP Notice:  Trying to get property of non-object in /data/release/dance/xjtudance/test/php/bmy_fun.php on line 339
PHP Fatal error:  Uncaught Error: Call to a member function find() on null in /data/release/dance/xjtudance/test/php/bmy_fun.php:374
Stack trace:
#0 /data/release/dance/xjtudance/test/php/bmy_fun.php(507): bmybbs->getArticle('http://bbs.xjtu...', 'Re: \xD6\xCA\xCE\xCA\xB0\xE6\xCE\xF1\xA3\xAC\xCB...')
#1 /data/release/dance/xjtudance/test/php/bmy_fun.php(489): bmybbs->getJinghua('http://bbs.xjtu...', '/T\xA1\xF9\xA1\xF9\xA1\xF9\xA1\xF9\xA1\xF9dan...', 0)
#2 /data/release/dance/xjtudance/test/php/bmy_fun.php(489): bmybbs->getJinghua('http://bbs.xjtu...', '/T\xA1\xF9\xA1\xF9\xA1\xF9\xA1\xF9\xA1\xF9dan...', 0)
#3 /data/release/dance/xjtudance/test/php/bmy_fun.php(489): bmybbs->getJinghua('http://bbs.xjtu...', '/T\xA1\xF9\xA1\xF9\xA1\xF9\xA1\xF9\xA1\xF9dan...', 0)
#4 /data/release/dance/xjtudance/test/php/bmy_fun.php(489): bmybbs->getJinghua('http://bbs.xjtu...', '/T\xA1\xF9\xA1\xF9\xA1\xF9\xA1\xF9\xA1\xF9dan...', 0)
#5 /data/release/dance/xjtudance/test/php/clone_bmyjinghua.php(20): bmybbs->getJinghua()
#6 {main}
  thrown in /data/release/dance/xjtudance/test/php/bmy_fun.php on line 374`

Apparently it is caused by [simple_html_dom.php](https://github.com/xjtudance/xjtudance/blob/master/dance_server/php/simple_html_dom.php), which is a old version of [PHP Simple HTML DOM Parser](http://sourceforge.net/projects/simplehtmldom/). Is there a way to solve this problem?

**Comment by jajupmochi** [comment]
Perhaps I can check [simple_html_dom.php](https://sourceforge.net/projects/simplehtmldom/) for newer version, but I doubt whether it will work.
